### ISSUE TITLE
Dependency on jdn missing from project.janet

### ISSUE THREAD

**Issue by MikeBeller** [livtanong/jdn-loader#2]
Hi @levitanong  -- I think jdn-loader depends on jdn, but it's not mentioned in project.janet.

**Comment by livtanong** [comment]
Nyaha, oops! Thanks for catching that, @MikeBeller! I had previously run `jpm install jdn`, so it was "there" without being defined in project.janet. So it never threw for me when I was running `jpm test`. 🤣

**Comment by MikeBeller** [comment]
thanks! -M
